import {
  HomeIcon,
  UserIcon,
  DocumentTextIcon,
  KeyIcon,
  MoonIcon,
  SunIcon,
  SparklesIcon,
  ArrowPathIcon,
  LockClosedIcon,
  AcademicCapIcon,
  ChatBubbleLeftRightIcon,
  PhotoIcon,
  FaceSmileIcon,
  ArrowsPointingOutIcon,
  QrCodeIcon,
  ArrowsRightLeftIcon,
  SwatchIcon,
  SpeakerWaveIcon,
  ClockIcon,
  ClipboardDocumentCheckIcon,
  TableCellsIcon,
  HashtagIcon,
  ArrowUpTrayIcon,
  CodeBracketIcon,
  FingerPrintIcon,
  PencilSquareIcon,
  CheckBadgeIcon,
  EyeDropperIcon,
  Square2StackIcon,
} from "@heroicons/react/24/outline";

export const navItems = [
  { path: "/", icon: HomeIcon, label: "Home" },
  {
    path: "/lorem-generator",
    icon: DocumentTextIcon,
    label: "Lorem Generator",
  },
  {
    path: "/case-converter",
    icon: ArrowPathIcon,
    label: "Case Converter",
  },
  {
    path: "/password-generator",
    icon: LockClosedIcon,
    label: "Password Generator",
  },
  {
    path: "/grammar-fixer",
    icon: AcademicCapIcon,
    label: "Grammar Fixer",
  },
  {
    path: "/better-comment",
    icon: ChatBubbleLeftRightIcon,
    label: "Better Comment",
  },
  {
    path: "/letter-profile-generator",
    icon: UserIcon,
    label: "Letter Profile",
  },
  {
    path: "/image-cropper",
    icon: PhotoIcon,
    label: "Image Cropper",
  },
  {
    path: "/joke-generator",
    icon: FaceSmileIcon,
    label: "Joke Generator",
  },
  {
    path: "/text-formatter",
    icon: PencilSquareIcon,
    label: "Text Formatter",
  },
  {
    path: "/image-shape-converter",
    icon: Square2StackIcon,
    label: "Image Shape",
  },
  {
    path: "/qr-code-generator",
    icon: QrCodeIcon,
    label: "QR Code",
  },
  {
    path: "/random-number-generator",
    icon: HashtagIcon,
    label: "Random Number",
  },
  {
    path: "/css-gradient-generator",
    icon: SwatchIcon,
    label: "CSS Gradient",
  },
  {
    path: "/text-to-speech",
    icon: SpeakerWaveIcon,
    label: "Text to Speech",
  },
  {
    path: "/online-stopwatch",
    icon: ClockIcon,
    label: "Online Stopwatch",
  },
  {
    path: "/todo-list-manager",
    icon: ClipboardDocumentCheckIcon,
    label: "Todo List Manager",
  },
  {
    path: "/json-to-csv",
    icon: TableCellsIcon,
    label: "JSON to CSV",
  },
  {
    path: "/number-formatter",
    icon: HashtagIcon,
    label: "Number Formatter",
  },
  {
    path: "/color-converter",
    icon: EyeDropperIcon,
    label: "Color Converter",
  },
  {
    path: "/image-resizer",
    icon: ArrowsPointingOutIcon,
    label: "Image Resizer",
  },
  {
    path: "/json-formatter",
    icon: CodeBracketIcon,
    label: "JSON Formatter",
  },
  {
    path: "/uuid-generator",
    icon: FingerPrintIcon,
    label: "UUID Generator",
  },
];
